"""
Signal Model - Trading signals generated by the signal engine.
"""
from datetime import datetime
from typing import Optional
from enum import Enum
from pydantic import BaseModel, Field
import uuid

class SignalType(str, Enum):
    STRONG_BUY = "STRONG_BUY"  # Edge >= 5%
    BUY = "BUY"                # Edge >= 3%
    HOLD = "HOLD"              # -3% < Edge < 3%
    SELL = "SELL"              # Edge <= 0%
    STRONG_SELL = "STRONG_SELL"  # Edge <= -5%
    SELL_INTO_STRENGTH = "SELL_INTO_STRENGTH"  # Late game, large lead

class Signal(BaseModel):
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    game_id: str
    market_id: str
    
    # Signal details
    signal_type: SignalType
    edge: float  # Calculated edge (fair_prob - market_prob)
    
    # Probabilities
    fair_prob: float
    market_prob: float
    
    # Confidence and volatility
    confidence: float = 0.0  # 0-1, based on model certainty
    volatility: float = 0.0  # Recent price volatility
    
    # Recommendation
    recommended_side: str  # "yes" or "no"
    recommended_size: float = 0.0  # Suggested position size in $
    max_loss: float = 0.0
    expected_value: float = 0.0
    
    # Game context
    score_diff: int
    time_remaining_seconds: int
    quarter: int
    
    # Timestamps
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    expires_at: Optional[datetime] = None  # Signal validity window
    
    @property
    def is_actionable(self) -> bool:
        """Whether this signal suggests a trade"""
        return self.signal_type in [
            SignalType.STRONG_BUY, 
            SignalType.BUY, 
            SignalType.SELL_INTO_STRENGTH
        ]
    
    @property
    def urgency(self) -> str:
        """Signal urgency level"""
        if self.signal_type == SignalType.STRONG_BUY:
            return "high"
        elif self.signal_type in [SignalType.BUY, SignalType.SELL_INTO_STRENGTH]:
            return "medium"
        return "low"
    
    def to_dict(self) -> dict:
        return {
            **self.dict(),
            'is_actionable': self.is_actionable,
            'urgency': self.urgency
        }
